version: '3.8'

services:
  app:
    build: .
    ports:
      - "3008:3008"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todo_database
      - API_KEY=1234
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: