openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:3008
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: secret-api-key
security:
  - ApiKeyAuth: []
paths:
  /api:
    get:
      summary: Get All Todos
      responses:
        '200':
          description: List of todos
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    post:
      summary: Create New Todo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Created Successfully
        '400':
          description: Missing Data
        '401': 
          description: Unauthorized
        '500':
          description: Internal Server Error
  /api/{id}:
    get:
      summary: Get Single Todo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Single Todo
        '401':
          description: Unauthorized
        '404':
          description: Todo not found
        '500':
          description: Internal Server Error
    patch:
      summary: Update Todo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200': 
          description: Updated Todo
        '401':
          description: Unauthorized
        '404':
          description: Todo not found
        '500':
          description: Internal Server Error
    delete:
      summary: Delete Todo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Deleted Successfully
        '401':
          description: Unauthorized
        '404':
          description: Todo not found
        '500':
          description: Internal Server Error
      


